from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy import Column, Integer, String, Enum, Boolean, Numeric
from app.enums.game_enums import MonthEnum, DayOfWeekEnum, FullTeamNameEnum, TeamAbbreviationEnum, DivisionEnum

Base = declarative_base()

class Game(Base):
    __tablename__ = 'games'
    id = Column(String, primary_key=True)
    id_string = Column(String, nullable=False)
    date = Column(String, nullable=False)
    month = Column(Enum(MonthEnum, native_enum=False, values_callable=lambda enum: [e.value for e in enum]), nullable=False)
    day = Column(Integer, nullable=False)
    year = Column(Integer, nullable=False)
    season = Column(String, nullable=False)
    day_of_week = Column(Enum(DayOfWeekEnum, native_enum=False, values_callable=lambda enum: [e.value for e in enum]), nullable=False)
    home_team = Column(Enum(FullTeamNameEnum, native_enum=False, values_callable=lambda enum: [e.value for e in enum]), nullable=False)
    home_abbreviation = Column(Enum(TeamAbbreviationEnum, native_enum=False, values_callable=lambda enum: [e.value for e in enum]), nullable=False)
    home_division = Column(Enum(DivisionEnum, native_enum=False, values_callable=lambda enum: [e.value for e in enum]), nullable=False)
    away_team = Column(Enum(FullTeamNameEnum, native_enum=False, values_callable=lambda enum: [e.value for e in enum]), nullable=False)
    away_abbreviation = Column(Enum(TeamAbbreviationEnum, native_enum=False, values_callable=lambda enum: [e.value for e in enum]), nullable=False)
    away_division = Column(Enum(DivisionEnum, native_enum=False, values_callable=lambda enum: [e.value for e in enum]), nullable=False)
    divisional = Column(Boolean, nullable=False)
    home_score = Column(Integer, nullable=False)
    away_score = Column(Integer, nullable=False)
    combined_score = Column(Integer, nullable=False)
    tie = Column(Boolean, nullable=False)
    winner = Column(Enum(FullTeamNameEnum, native_enum=False, values_callable=lambda enum: [e.value for e in enum]), nullable=False)
    loser = Column(Enum(FullTeamNameEnum, native_enum=False, values_callable=lambda enum: [e.value for e in enum]), nullable=False)
    spread = Column(Numeric(precision=4, scale=1), nullable=False)
    home_spread = Column(Numeric(precision=4, scale=1), nullable=False)
    home_spread_result = Column(Integer, nullable=False)
    away_spread = Column(Numeric(precision=4, scale=1), nullable=False)
    away_spread_result = Column(Integer, nullable=False)
    spread_push = Column(Boolean, nullable=False)
    pk = Column(Boolean, nullable=False)
    total = Column(Numeric(precision=4, scale=1), nullable=False)
    total_push = Column(Boolean, nullable=False)
    home_favorite = Column(Boolean, nullable=False)
    away_underdog = Column(Boolean, nullable=False)
    away_favorite = Column(Boolean, nullable=False)
    home_underdog = Column(Boolean, nullable=False)
    home_win = Column(Boolean, nullable=False)
    away_win = Column(Boolean, nullable=False)
    favorite_win = Column(Boolean, nullable=False)
    underdog_win = Column(Boolean, nullable=False)
    home_favorite_win = Column(Boolean, nullable=False)
    away_underdog_win = Column(Boolean, nullable=False)
    away_favorite_win = Column(Boolean, nullable=False)
    home_underdog_win = Column(Boolean, nullable=False)
    home_cover = Column(Boolean, nullable=False)
    away_cover = Column(Boolean, nullable=False)
    favorite_cover = Column(Boolean, nullable=False)
    underdog_cover = Column(Boolean, nullable=False)
    home_favorite_cover = Column(Boolean, nullable=False)
    away_underdog_cover = Column(Boolean, nullable=False)
    away_favorite_cover = Column(Boolean, nullable=False)
    home_underdog_cover = Column(Boolean, nullable=False)
    over_hit = Column(Boolean, nullable=False)
    under_hit = Column(Boolean, nullable=False)

    def __repr__(self):
        return f'<Game(id={self.id_string}, date={self.date}, season={self.season}, home={self.home_abbreviation}, away={self.away_abbreviation})>'
