from enum import Enum

class MonthEnum(str, Enum):
    JANUARY = "January"
    FEBRUARY = "February"
    MARCH = "March"
    APRIL = "April"
    MAY = "May"
    JUNE = "June"
    JULY = "July"
    AUGUST = "August"
    SEPTEMBER = "September"
    OCTOBER = "October"
    NOVEMBER = "November"
    DECEMBER = "December"

class DayOfWeekEnum(str, Enum):
    SUNDAY = "Sunday"
    MONDAY = "Monday"
    TUESDAY = "Tuesday"
    WEDNESDAY = "Wednesday"
    Thursday = "Thursday"
    FRIDAY = "Friday"
    SATURDAY = "Saturday"

class FullTeamNameEnum(str, Enum):
    NYJ = "New York Jets"
    NE = "New England Patriots"
    BUF = "Buffalo Bills"
    MIA = "Miami Dolphins"
    PIT = "Pittsburgh Steelers"
    BAL = "Baltimore Ravens"
    CIN = "Cincinnati Bengals"
    CLE = "Cleveland Browns"
    TEN = "Tennessee Titans"
    IND = "Indianapolis Colts"
    JAX = "Jacksonville Jaguars"
    HOU = "Houston Texans"
    KC = "Kansas City Chiefs"
    LAC = "Los Angeles Chargers"
    LV = "Las Vegas Raiders"
    DEN = "Denver Broncos"
    DAL = "Dallas Cowboys"
    PHI = "Philadelphia Eagles"
    NYG = "New York Giants"
    WAS = "Washington Commanders"
    CHI = "Chicago Bears"
    MIN = "Minnesota Vikings"
    GB = "Green Bay Packers"
    DET = "Detroit Lions"
    ATL = "Atlanta Falcons"
    NO = "New Orleans Saints"
    CAR = "Carolina Panthers"
    TB = "Tampa Bay Buccaneers"
    ARI = "Arizona Cardinals"
    SEA = "Seattle Seahawks"
    SF = "San Francisco 49ers"
    LAR = "Los Angeles Rams"

class TeamAbbreviationEnum(str, Enum):
    NYJ = "NYJ"
    NE = "NE"
    BUF = "BUF"
    MIA = "MIA"
    PIT = "PIT"
    BAL = "BAL"
    CIN = "CIN"
    CLE = "CLE"
    TEN = "TEN"
    IND = "IND"
    JAX = "JAX"
    HOU = "HOU"
    KC = "KC"
    LAC = "LAC"
    LV = "LV"
    DEN = "DEN"
    DAL = "DAL"
    PHI = "PHI"
    NYG = "NYG"
    WAS = "WAS"
    CHI = "CHI"
    MIN = "MIN"
    GB = "GB"
    DET = "DET"
    ATL = "ATL"
    NO = "NO"
    CAR = "CAR"
    TB = "TB"
    ARI = "ARI"
    SEA = "SEA"
    SF = "SF"   
    LAR = "LAR"

class DivisionEnum(str, Enum):
    AFC_EAST = "AFC EAST"
    AFC_NORTH = "AFC NORTH"
    AFC_SOUTH = "AFC SOUTH"
    AFC_WEST = "AFC WEST"
    NFC_EAST = "NFC EAST"
    NFC_NORTH = "NFC NORTH"
    NFC_SOUTH = "NFC SOUTH"
    NFC_WEST = "NFC WEST"